CV_flag: False
add_vocab_flag: False
LLRD_flag: False
aug_flag: False
aug_special_flag: False
model_indicator: 'pretrain'
aug_indicator:

vocab_sup_file: 'vocab/vocab_sup_PE_I.csv'
train_file: 'data/merged/train_Multi_POINT2.csv'
test_file: 'data/merged/test_Multi_POINT2.csv'
model_path: 'ckpt/pretrain.pt'
save_path: 'ckpt/model_multi_boost_train.pt'
best_model_path: 'ckpt/model_multi_boost_best.pt'
scaler_path: 'ckpt/scaler_multi_boost.joblib'

# Properties for Multi-task (keeping multi-task but focusing on merged Tg)
target_cols: ['Tg', 'FFV', 'Tc', 'Density', 'Rg']

k: 5
blocksize: 128
batch_size: 4
num_epochs: 30
warmup_ratio: 0.1
drop_rate: 0.1
lr_rate: 0.00005
lr_rate_reg: 0.0001
weight_decay: 0.01
hidden_dropout_prob: 0.1
attention_probs_dropout_prob: 0.1
tolerance: 10
num_workers: 0
